vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: /uploads/images/products
            upload_destination: "%kernel.project_dir%/public/uploads/images/products"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
