controllers:
    resource: "../src/Controller/"
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

admin:
    resource: "../src/Controller/Admin/"
    type: attribute
    prefix: /admin
