parameters:
    images_directory: "%kernel.project_dir%/public/uploads/images"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        # config/services.yaml
    App\Command\CreateUserCommand:
        tags: ["console.command"]

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\EventListener\ProductListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
